### ISSUE TITLE
K8s ingress api service return 502 

### ISSUE THREAD

**Issue by travishen** [FroggyTaipei/froggy-service#127]
## 問題
完成事項
* [x]把資料庫加到default vpc
* [x]建立secrets用於backend環境變數
* [x]建立服務api-service, port 8000
* [x]確認資料庫連線正常
* [x]確認所有工作負載執行狀態為正常

錯誤訊息
* 呼叫api如`<lb ip>/api/docs`回傳Server Error: 502

## services
api-service
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"8000":"froggy-service-backendconfig"}}'
  creationTimestamp: 2019-01-31T13:21:17Z
  labels:
    app: api
  name: api-service
  namespace: default
  resourceVersion: "265416"
  selfLink: /api/v1/namespaces/default/services/api-service
  uid: 174852bf-255b-11e9-96e0-4201aca00004
spec:
  clusterIP: 10.0.0.99
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31992
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: api
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
```

## ingress
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: froggy-service-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: nginx-service
          servicePort: 80
        path: /
      - backend:
          serviceName: api-service
          servicePort: 8000
        path: /api
```

**Comment by travishen** [comment]
brief:
如果服務的heathcheck失敗，Ingress針對該service的routing會回傳502

1. 根據[All Kubernetes services must serve a 200 page on '/'](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/cluster-loadbalancing/glbc#prerequisites)，於api server新增home page，回傳200
```
urlpatterns = [
    path('', home, name='home'),  # All Kubernetes services must serve a 200 page on '/'
    ...
]
```
2. [Kubernetes Health Checks in Django](https://www.ianlewis.org/en/kubernetes-health-checks-django)參照這篇設定liveliness, readiness（這個步驟只是額外做的設定，照第一點設定即可解此issue）
```
    spec:
      containers:
      - command:
        - /app/scripts/gunicorn.sh
        envFrom:
        - secretRef:
            name: environs
        image: gcr.io/genial-bonbon-226211/froggy-service-api@sha256:5a39b332d7374a61a6ca2e211cf0f23583f8de58f4e6df78adbe279376ba6d88
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: webapp-port
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 30
        name: froggy-service-api-sha256
        ports:
        - containerPort: 8000
          name: webapp-port
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readiness
            port: webapp-port
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 30
```

參考：https://stackoverflow.com/questions/45884131/kubernetes-ingress-reports-backend-as-unhealthy-though-all-pods-are-running-an
