### ISSUE TITLE
Remove credential file from api image

### ISSUE THREAD

**Issue by travishen** [FroggyTaipei/froggy-service#149]
CI在deploy的部份流程需要改善，目前在build後端映像檔時，會複製gs_credential.json到backend資料夾，當初這樣做是為了跑正式環境的測試，但有幾個缺點：

* 不安全：有deploy到public docker hub repo，雖然build之前會先移除，但production跟stage都有這個檔案，之後修改上有可能不小心就放進去
* 因為要移除gs_credential.json，變成deploy要重複build，只為了一個檔案

可以更改的方向：
* .travis.yaml: 在install的地方去判斷如果是master且非pull request，在`docker-compose up`時mount gs_credential.json，這樣一來public, stage, production都不會有這個檔案，等於是共用同一份映像檔
* docker_deploy.sh: 移除重複的build
* GKE上面的deployment再把gs_credential.json的secret mount到容器中：
```
        volumeMounts:
        - name: gs-credential
          mountPath: /app/gs_credential.json
          readOnly: true
          subPath: gs_credential.json
      volumes:
      - name: gs-credential
        secret:
          secretName: gs-credential
```

至於nginx的映像檔因為是webpack，不能動態讀取env，所以還是要分開build
