### ISSUE TITLE
Nginx liveness, readiness heathcheck

### ISSUE THREAD

**Issue by travishen** [FroggyTaipei/froggy-service#151]
* liveness: check nginx is alive e.g. curl 127.0.0.1:80
* readiness: check backend api are avaliable

**Comment by travishen** [comment]
Access api through service(Cluster IP):
* Add ALLOWD_HOST: https://github.com/mozmeao/django-allow-cidr

**Comment by travishen** [comment]
Service的Cluster IP在某程度上來說也是不穩定的，比較好的作法是透過Service Discovery:
* DNS
* Environment Variable

比較推薦的方式是DNS:
1. 透過`kubectl get service --namespace=kube-system`可以找到`kube-dns`服務
2. Service建立時會在此dns服務器上自動加上一條紀錄

```
/ # nslookup api-service
nslookup: can't resolve '(null)': Name does not resolve

Name:      api-service
Address 1: 10.0.0.99 api-service.default.svc.cluster.local
```

Django的ALLOWED_HOST還是要加上service name，例如api-service

**Comment by travishen** [comment]
承上，
* nginx build先安裝curl
```
RUN apk add curl
```
* 在deployment yaml加上liveness, readness
```
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - curl
            - api-service:8000/readiness
          initialDelaySeconds: 5
          periodSeconds: 5
```
* Django的ALLOWED_HOST加上api-service

手動測試
```
/ # curl api-service:8000/readiness
OK/ # 
```
log 
```
ssivart@xps13:~$ kubectl logs -l app=nginx --namespace=stage
10.140.0.16 - - [15/Feb/2019:07:24:58 +0000] "GET / HTTP/1.1" 200 1948 "-" "GoogleHC/1.0"
10.140.0.15 - - [15/Feb/2019:07:24:58 +0000] "GET / HTTP/1.1" 200 1948 "-" "GoogleHC/1.0"
10.140.0.15 - - [15/Feb/2019:07:24:58 +0000] "GET / HTTP/1.1" 200 1948 "-" "GoogleHC/1.0"
10.140.0.16 - - [15/Feb/2019:07:24:58 +0000] "GET / HTTP/1.1" 200 1948 "-" "GoogleHC/1.0"
10.44.1.1 - - [15/Feb/2019:07:24:58 +0000] "GET / HTTP/1.1" 200 1948 "-" "GoogleHC/1.0"
10.140.0.16 - - [15/Feb/2019:07:24:58 +0000] "GET / HTTP/1.1" 200 1948 "-" "GoogleHC/1.0"
10.140.0.15 - - [15/Feb/2019:07:24:58 +0000] "GET / HTTP/1.1" 200 1948 "-" "GoogleHC/1.0"
10.44.1.1 - - [15/Feb/2019:07:24:59 +0000] "GET / HTTP/1.1" 200 1948 "-" "GoogleHC/1.0"
10.44.1.1 - - [15/Feb/2019:07:25:04 +0000] "GET / HTTP/1.1" 200 1948 "-" "kube-probe/1.10+"
10.44.1.1 - - [15/Feb/2019:07:25:14 +0000] "GET / HTTP/1.1" 200 1948 "-" "kube-probe/1.10+"
```
